# 1. Cổng chạy Backend
server.port=8080

# 2. Kết nối Database MySQL (Aiven Cloud)
spring.datasource.url=jdbc:mysql://mysql-303bfd52-trinhcongvinh1326-8733.l.aivencloud.com:14937/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Ob34jBazwKyxQJx3cQw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

brevo.api.key=${BREVO_API_KEY}
# 4. Ngắt kết nối hoàn toàn với các dịch vụ Mail cũ của Google
# Không khai báo bất kỳ dòng spring.mail.* nào ở đây nữa!