# 1. Cấu hình cổng chạy backend
server.port=8080

# 2. Cấu hình kết nối MySQL TRÊN MÂY (AIVEN)
# Chỗ này đã đổi từ localhost sang server của Aiven mày vừa tạo
spring.datasource.url=jdbc:mysql://mysql-1764640f-trinhcongvinh1326-8733.j.aivencloud.com:14939/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_oP23tP8fC7Nf1eUu3fD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Cấu hình JPA / Hibernate (Tự động xây bảng trên mây)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sử dụng Dialect bản 8 cho MySQL trên mây
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Lưu ý: Phần cấu hình Mail mày đã viết bằng code Java (file MailConfig)
# và dùng biến EMAIL_PASS nên không cần khai báo mật khẩu ở đây nữa cho an toàn.